name: Deploy a EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Subir archivos a EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."                      
          target: "/home/ubuntu/projects/licenses"     

      - name: Ejecutar comandos en EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 600 server.pem
          ssh -i server.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            # Cargar nvm
            source ~/.nvm/nvm.sh

            # Usar la versión de Node.js instalada
            nvm use 22.14.0

            cd /home/ubuntu/projects/licenses
            npm install 
            nohup npm start &
          EOF

      - name: Verificar si el servidor está corriendo
        run: |
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 600 server.pem
          ssh -i server.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} "pgrep -fl 'node' || echo 'No se encontró el proceso 😬'"
