name: Deploy a EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Subir archivos a EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."                      
          target: "/home/ubuntu/projects/licenses"     

      - name: Ejecutar comandos en EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 600 server.pem
          ssh -i server.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            # Cargar nvm
            source ~/.nvm/nvm.sh
            nvm use 22.14.0

            # Ir al proyecto
            cd /home/ubuntu/projects/licenses

            # Instalar dependencias
            npm install

            # Matar proceso Node.js si ya está en uso
            fuser -k 4000/tcp || true

            # Iniciar app en segundo plano
            nohup npm start &

            # Instalar Nginx si no está
            if ! command -v nginx &> /dev/null; then
              sudo apt update
              sudo apt install nginx -y
            fi

            # Configurar Nginx como proxy reverso
            sudo tee /etc/nginx/sites-available/default > /dev/null <<EOCONFIG
          server {
          listen 80 default_server;
          listen [::]:80 default_server;
    
          server_name _;
      
          location / {
            proxy_pass http://localhost:4000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host \$host;
            proxy_cache_bypass \$http_upgrade;
          }
          }
          EOCONFIG

            # Reiniciar Nginx para aplicar cambios
            sudo systemctl restart nginx
          EOF
      - name: Verificar si el servidor está corriendo
        run: |
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 600 server.pem
          ssh -i server.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} "pgrep -fl 'node' || echo 'No se encontró el proceso 😬'"
